PRAGMA foreign_keys = OFF;
DROP TABLE IF EXISTS urls;

CREATE TABLE urls (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    url TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
