#: schema https://esm.sh/wrangler/config-schema.json
# https://developers.cloudflare.com/workers/wrangler/configuration
name = "url-shortener"
keep_vars = true
main = "./build/worker/shim.mjs"
compatibility_date = "2024-11-01"

workers_dev = true
vars = { ENVIRONMENT = "development" }

d1_databases = [
  { binding = "DB", database_name = "url-short-d1", database_id = "3da5b327-e066-4915-a8dd-22cddbcbcf0b" },
]

[build]
command = "cargo install --quiet worker-build && worker-build --release"

[env.production]
name = "url-shortener"
workers_dev = true
vars = { ENVIRONMENT = "production" }

d1_databases = [
  { binding = "DB", database_name = "url-short-d1", database_id = "3da5b327-e066-4915-a8dd-22cddbcbcf0b" },
]

# https://developers.cloudflare.com/workers/observability/logs/workers-logs/
[env.production.observability]
enabled = true
