name: Deploy

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

defaults:
  run:
    shell: bash

env:
  NAME: 'url-shortener'
  CARGO_TERM_COLOR: 'always'
  ACTIONS_RUNNER_DEBUG: true

jobs:
  deploy:
    runs-on: ['ubuntu-latest']
    steps:
      - name: 🔑 Checkout
        uses: actions/checkout@v4

      - name: 🦀 Set up Rust
        run: |
          rustup set auto-self-update disable
          rustup toolchain install 1.81.0 --profile minimal
          rustup default 1.81.0

      - uses: Swatinem/rust-cache@v2.7.5
        with:
          prefix-key: v0 # increment this to bust the cache if needed

      - name: Install sccache
        uses: mozilla-actions/sccache-action@v0.0.6
        env:
          RUSTC_WRAPPER: 'sccache'
          SCCACHE_GHA_ENABLED: true

      - name: 🛠️ Build worker
        run: cargo install --quiet worker-build && worker-build --release

      - name: 🐰 Set up Bun
        uses: oven-sh/setup-bun@main
        with:
          bun-version: 'latest'

      - name: 🔸 Cloudflare Workers - Deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          bun x wrangler@latest deploy \
            --env='production' \
            --config='wrangler.toml'
